/* confdefs.h */
#define PACKAGE_NAME "reaver"
#define PACKAGE_TARNAME "reaver"
#define PACKAGE_VERSION "1.4"
#define PACKAGE_STRING "reaver 1.4"
#define PACKAGE_BUGREPORT ""
#define PACKAGE_URL ""
#define HAVE_LIBPCAP 1
#define HAVE_LIBSQLITE3 1
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STDINT_H 1
#define HAVE_STRING_H 1
#define HAVE_PCAP_H 1
#define HAVE_SQLITE3_H 1
